spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/football
    username: <user>
    password: <password>

management:
  endpoints:
    web:
      exposure:
        include: health,env,metrics,beans,loggers,football
  endpoint:
    health:
      probes:
        enabled: true

football:
  folder: teams